version: '3.9'
services:
  user-ros:
    build: ./user/
    privileged: true
    environment:
      - "ROS_MASTER_URI=http://user-ros:11311"
      - "ROS_HOSTNAME=user-ros"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    restart: on-failure
    command: tail -f /dev/null